
export const homepageConfig = [
  // {
  //   id: "hero-banner",
  //   type: "banner",
  //   title: "Big Summer Sale ",
  //   subtitle: "Up to 50% off on top brands",
  //   ctaText: "Shop Now",
  //   ctaLink: "/products",
  //   bgColor: "#FFE5D4",
  //   image: "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/thumbnail.webp"
  // },
  // {
  //   id: "smartphones-slider",
  //   type: "slider",
  //   title: "Best Smartphones",
  //   slug: "smartphones",
  //   limit: 12,
  //   viewAllLink: "/category/smartphones",
  // },
  // {
  //   id: "mobile-accessories-slider",
  //   type: "slider",
  //   title: "mobile-accessories",
  //   slug: "mobile-accessories",
  //   limit: 12,
  //   viewAllLink: "/category/smartphones",
  // },
  // {
  //   id: "smartphones-grid",
  //   type: "grid",
  //   title: "smartphones Deals",
  //   slug: "smartphones",
  //   start: 4,
  //   viewAllLink: "/category/furniture",
  // },
  // {
  //   id: "furniture-grid",
  //   type: "grid",
  //   title: "Furniture Deals",
  //   slug: "furniture",
  //   start: 4,
  //   viewAllLink: "/category/furniture",
  // },
  // {
  //   id: "mobile-accessories-grid",
  //   type: "grid",
  //   title: "mobile-accessories Deals",
  //   slug: "mobile-accessories",
  //   start: 4,
  //   viewAllLink: "/category/furniture",
  // },
  // {
  //   id: "groceries-grid",
  //   type: "grid",
  //   title: "groceries Deals",
  //   slug: "groceries",
  //   start:16,
  //   viewAllLink: "/category/furniture",
  // },

  // Banner section
  {
    id: "hero-banner",
    type: "banner",
    title: "Big Summer Sale ",
    subtitle: "Up to 50% off on top brands",
    ctaText: "Shop Now",
    ctaLink: "/products",
    bgColor: "#FFE5D4",
    image: "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/thumbnail.webp"
  },

  // Grid
  {
    id: "beauty-grid",
    type: "grid",
    slug: "fragrances",
    start: 0,
    viewAllLink: "/category/beauty",
  },
  {
    id: "electronics-grid",
    type: "grid",
    slug: "smartphones",
    start: 0,
    viewAllLink: "/category/electronics",
  },
  {
    id: "mens-fashion-grid",
    type: "grid",
    slug: "mens-shirts",
    start: 0,
    viewAllLink: "/category/mens-fashion",
  },
  {
    id: "womens-fashion-grid",
    type: "grid",
    slug: "womens-dresses",
    start: 0,
    viewAllLink: "/category/womens-fashion",
  },
  {
    id: "groceries-grid",
    type: "grid",
    slug: "groceries",
    start: 0,
    viewAllLink: "/category/groceries",
  },
  {
    id: "home-living-grid",
    type: "grid",
    slug: "furniture",
    start: 0,
    viewAllLink: "/category/home-living",
  },
  {
    id: "vehicles-grid",
    type: "grid",
    slug: "motorcycle",
    start: 0,
    viewAllLink: "/category/vehicles",
  },
  {
    id: "sports-grid",
    type: "grid",
    slug: "sports-accessories",
    start: 0,
    viewAllLink: "/category/sports",
  },

  {
    id: "laptop-grid",
    type: "grid",
    slug: "laptops",
    start: 0,
    viewAllLink: "/",
  },
  {
    id: "tablet-grid",
    type: "grid",
    slug: "tablets",
    start: 0,
    viewAllLink: "/",
  },

  {
    id: "beautyProducts-grid",
    type: "grid",
    slug: "beauty",
    start: 0,
    viewAllLink: "/",
  },
  {
    id: "skincare-grid",
    type: "grid",
    slug: "skin-care",
    start: 0,
    viewAllLink: "/",
  },

  {
    id: "bike-grid",
    type: "grid",
    slug: "motorcycle",
    start: 0,
    viewAllLink: "/",
  },
  {
    id: "car-grid",
    type: "grid",
    slug: "vehicle",
    start: 0,
    viewAllLink: "/",
  },

  {
    id: "womens-watches-grid",
    type: "grid",
    slug: "womens-watches",
    start: 0,
    viewAllLink: "/",
  },
  {
    id: "womens-shoes-grid",
    type: "grid",
    slug: "womens-shoes",
    start: 0,
    viewAllLink: "/",
  },
  {
    id: "womens-bags-grid",
    type: "grid",
    slug: "womens-bags",
    start: 0,
    viewAllLink: "/",
  },
  {
    id: "womens-tops-grid",
    type: "grid",
    slug: "tops",
    start: 0,
    viewAllLink: "/",
  },

  {
    id: "mens-watches-grid",
    type: "grid",
    slug: "mens-watches",
    start: 0,
    viewAllLink: "/",
  },
  {
    id: "mens-shoes-grid",
    type: "grid",
    slug: "mens-shoes",
    start: 0,
    viewAllLink: "/",
  },


  // Slider section
  {
    id: "smartphones-slider",
    type: "slider",
    slug: "smartphones",
    limit: 12,
    viewAllLink: "/",
  },
  {
    id: "mobile-accessories-slider",
    type: "slider",
    slug: "mobile-accessories",
    limit: 12,
    viewAllLink: "/",
  },
  {
    id: "groceries-slider",
    type: "slider",
    slug: "groceries",
    limit: 12,
    viewAllLink: "/",
  },
  {
    id: "kitchen-accessories-slider",
    type: "slider",
    slug: "kitchen-accessories",
    limit: 12,
    viewAllLink: "/",
  },
  // {
  //   id: "sunglasses-slider",
  //   type: "slider",
  //   slug: "sunglasses",
  //   limit: 12,
  //   viewAllLink: "/",
  // },
  {
    id: "sports-slider",
    type: "slider",
    slug: "sports-accessories",
    limit: 12,
    viewAllLink: "/",
  },
];