
export const homepageConfig = [
  {
    id: "hero-banner",
    type: "banner",
    title: "Big Summer Sale ",
    subtitle: "Up to 50% off on top brands",
    ctaText: "Shop Now",
    ctaLink: "/products",
    bgColor: "#FFE5D4",
    image: "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/thumbnail.webp"
  },
  {
    id: "smartphones-slider",
    type: "slider",
    title: "Best Smartphones",
    slug: "smartphones",
    limit: 12,
    viewAllLink: "/category/smartphones",
  },
  {
    id: "mobile-accessories-slider",
    type: "slider",
    title: "mobile-accessories",
    slug: "mobile-accessories",
    limit: 12,
    viewAllLink: "/category/smartphones",
  },
  {
    id: "smartphones-grid",
    type: "grid",
    title: "smartphones Deals",
    slug: "smartphones",
    limit: 4,
    viewAllLink: "/category/furniture",
  },
  {
    id: "furniture-grid",
    type: "grid",
    title: "Furniture Deals",
    slug: "furniture",
    limit: 4,
    viewAllLink: "/category/furniture",
  },
  {
    id: "mobile-accessories-grid",
    type: "grid",
    title: "mobile-accessories Deals",
    slug: "mobile-accessories",
    limit: 4,
    viewAllLink: "/category/furniture",
  },
  {
    id: "groceries-grid",
    type: "grid",
    title: "groceries Deals",
    slug: "groceries",
    limit: 4,
    viewAllLink: "/category/furniture",
  },
];